backend:
  name: git-gateway
  branch: main
  repo: EleazarFreitas/DecapCMS

local_backend: false

media_folder: "uploads"
public_folder: "/uploads"

# Essencial para que o preview funcione com caminhos absolutos
media_folder_relative: false

publish_mode: editorial_workflow

collections:
  - name: "home"
    label: "Home"
    files:
      - file: "_data/home.yml"
        label: "Conteúdo da Home"
        name: "home_content"
        fields:
          - { label: "Título da Página", name: "title", widget: "string" }
          - label: "Lista de Cards"
            name: "cards"
            widget: "list"
            fields:
              - { label: "Título do Card", name: "card_title", widget: "string" }
              - { label: "Descrição", name: "card_desc", widget: "text" }
              - { label: "Imagem", name: "card_img", widget: "image" }
              - { label: "Link do Botão", name: "card_link", widget: "string" }